x-logging: &logging
 logging:
   driver: json-file
   options:
     max-size: 100m
     max-file: "3"
     tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

# Legacy compose.yml - Networks now managed by DICKS system
# Individual services use isolated networks (ethnode1-net, ethnode2-net, etc.)
networks:
  default:
    external: true
    name: monitoring-net
    enable_ipv6: ${IPV6:-false}
