x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  mevboost:
    container_name: ${NODE_NAME}-mevboost
    restart: "unless-stopped"
    image: flashbots/mev-boost:${MEVBOOST_VERSION}
    pull_policy: always
    user: "${NODE_UID}:${NODE_GID}"
    stop_grace_period: 1m
    environment:
      - NETWORK=${NETWORK}
    ports:
      - ${HOST_IP:-}:${MEVBOOST_PORT}:${MEVBOOST_PORT}/tcp
    networks:
      default:
        aliases:
          - mevboost
          - ${NODE_NAME}-mevboost
    <<: *logging
    entrypoint:
      - /app/mev-boost
      - -${NETWORK}
      - -addr=0.0.0.0:${MEVBOOST_PORT}
      - -relay-check
      - -relays=${MEVBOOST_RELAY}
    labels:
      - prometheus.scrape=false
      - prometheus.instance=mevboost
      - prometheus.network=${NETWORK}

networks:
  default:
    enable_ipv6: ${IPV6:-false}
