x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    container_name: ${NODE_NAME}-nethermind
    restart: "unless-stopped"
    image: nethermind/nethermind:${NETHERMIND_VERSION}
    pull_policy: always
    user: "${NODE_UID}:${NODE_GID}"
    stop_grace_period: 5m
    stop_signal: SIGINT
    environment:
      - EL_EXTRAS=${EL_EXTRAS:-}
      - ARCHIVE_NODE=${EL_ARCHIVE_NODE:-false}
      - MINIMAL_NODE=${EL_MINIMAL_NODE:-false}
      - AUTOPRUNE_NM=${AUTOPRUNE_NM:-true}
      - NETWORK=${NETWORK}
    volumes:
      - ./data/execution:/var/lib/nethermind
      - /etc/localtime:/etc/localtime:ro
      - ./jwt:/var/lib/nethermind/ee-secret
    ports:
      - ${HOST_IP:-}:${EL_RPC_PORT}:8545/tcp
      - ${HOST_IP:-}:${EL_WS_PORT}:8546/tcp
      - ${HOST_IP:-}:${EE_PORT}:8551/tcp
      - ${HOST_IP:-}:6060:6060/tcp
      - ${HOST_IP:-}:${EL_P2P_PORT}:${EL_P2P_PORT}/tcp
      - ${HOST_IP:-}:${EL_P2P_PORT}:${EL_P2P_PORT}/udp
    networks:
      default:
        aliases:
          - eth1
          - execution
          - ${EXECUTION_ALIAS:-default-execution}
    <<: *logging
    entrypoint:
      - /nethermind/nethermind
      - --config=${NETWORK}
      - --Init.WebSocketsEnabled=true
      - --Network.DiscoveryPort=${EL_P2P_PORT}
      - --Network.P2PPort=${EL_P2P_PORT}
      - --Network.MaxActivePeers=${EL_MAX_PEER_COUNT}
      - --HealthChecks.Enabled=true
      - --HealthChecks.UIEnabled=true
      - --JsonRpc.Enabled=true
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.Port=8545
      - --JsonRpc.WebSocketsPort=8546
      - --JsonRpc.EngineHost=0.0.0.0
      - --JsonRpc.EnginePort=8551
      - --JsonRpc.AdditionalRpcUrls=http://127.0.0.1:1337|http|admin
      - --JsonRpc.JwtSecretFile=/var/lib/nethermind/ee-secret/jwtsecret
      - --Metrics.Enabled=true
      - --Metrics.ExposeHost=0.0.0.0
      - --Metrics.ExposePort=6060
      - --Pruning.FullPruningCompletionBehavior=AlwaysShutdown
      - --log=INFO
      - --datadir=/var/lib/nethermind
    labels:
      - prometheus.scrape=true
      - prometheus.job=nethermind
      - prometheus.port=6060
      - prometheus.path=/metrics
      - ethereum.client=nethermind
      - ethereum.layer=execution
      - ethereum.network=${NETWORK}

networks:
  default:
    enable_ipv6: ${IPV6:-false}
