x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    container_name: ${NODE_NAME}-reth
    image: ghcr.io/paradigmxyz/reth:${RETH_VERSION}
    restart: unless-stopped
    stop_grace_period: 1m
    stop_signal: SIGINT
    user: "${NODE_UID}:${NODE_GID}"
    ports:
      - "${HOST_IP:-}:${EL_RPC_PORT}:8545"
      - "${HOST_IP:-}:${EL_WS_PORT}:8546"
      - "${HOST_IP:-}:${EE_PORT}:8551"
      - "${HOST_IP:-}:9001:9001"
      - "${HOST_IP:-}:${EL_P2P_PORT}:${EL_P2P_PORT}/tcp"
      - "${HOST_IP:-}:${EL_P2P_PORT}:${EL_P2P_PORT}/udp"
      - "${HOST_IP:-}:${EL_P2P_PORT_2}:${EL_P2P_PORT_2}/udp"
    volumes:
      - ./data/execution:/opt/reth/data
      - ./jwt:/opt/reth/jwt:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        aliases:
          - eth1
          - execution
          - ${EXECUTION_ALIAS:-default-execution}
    <<: *logging
    command:
      - "node"
      - "--chain"
      - "${NETWORK}"
      - "--datadir"
      - "/opt/reth/data"
      - "--port"
      - "${EL_P2P_PORT}"
      - "--discovery.port"
      - "${EL_P2P_PORT}"
      - "--enable-discv5-discovery"
      - "--discovery.v5.port"
      - "${EL_P2P_PORT_2}"
      - "--http"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.port"
      - "8545"
      - "--http.api"
      - "eth,net,web3,debug,trace"
      - "--http.corsdomain"
      - "http://127.0.0.1,http://localhost"
      - "--ws"
      - "--ws.addr"
      - "0.0.0.0"
      - "--ws.port"
      - "8546"
      - "--ws.origins"
      - "http://127.0.0.1,http://localhost"
      - "--authrpc.addr"
      - "0.0.0.0"
      - "--authrpc.port"
      - "8551"
      - "--authrpc.jwtsecret"
      - "/opt/reth/jwt/jwtsecret"
      - "--metrics"
      - "0.0.0.0:9001"
      - "--max-outbound-peers"
      - "${EL_MAX_PEER_COUNT}"
      - "--log.file.directory"
      - "/opt/reth/data/logs"
    labels:
      - prometheus.scrape=true
      - prometheus.job=reth
      - prometheus.port=9001
      - prometheus.path=/metrics
      - ethereum.client=reth
      - ethereum.layer=execution
      - ethereum.network=${NETWORK}

networks:
  default:
    enable_ipv6: ${IPV6:-false}
