name: Update Version

on:
  push:
    branches: [ main ]

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Get current version
      id: get_version
      run: |
        VERSION=$(grep -oP 'v\d+\.\d+\.\d+' nodeboi.sh | head -1)
        echo "current=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Bump version
      id: bump
      run: |
        VERSION="${{ steps.get_version.outputs.current }}"
        VERSION=${VERSION#v}
        IFS='.' read -r major minor patch <<< "$VERSION"
        patch=$((patch + 1))
        NEW_VERSION="v${major}.${minor}.${patch}"
        echo "new=$NEW_VERSION" >> $GITHUB_OUTPUT
    
    - name: Update files
      run: |
        sed -i "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/${{ steps.bump.outputs.new }}/g" nodeboi.sh install.sh
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add -A
        git commit -m "Bump version to ${{ steps.bump.outputs.new }}"
        git push
